### ISSUE TITLE
previously run version 1.0 scripts re-run when use version 1.1

### ISSUE THREAD

**Issue by OzBob** [grate-devs/grate#108]
I'm seeking clarification on the use of the --version option mentioned in #8 

If I use the [example script powershell](https://github.com/erikbra/grate/blob/main/examples/local/run-migration.ps1#L10):

```
grate `
--files=.\db `
--env=Local `
--connstring="Server=(localdb)\MSSQLLocalDB;Integrated Security=true;Database=grate_test" `
--version=1.0 
```

It all works fine.

If I run it a 2nd time with the env=Test, it works as described and only the 'Test' script from the 'up' folder is executed, but...

Change the ```--version=1.1``` and it runs all the ['one time'](https://github.com/erikbra/grate/blob/main/docs/ScriptTypes/OneTimeScripts.md) scripts again.

How should the semantic version control work?

Do script files have a version number added into the file name like the ```ENV```` keyword?

**Comment by erikbra** [comment]
It definitely looks like we have a bug on the version_id, @wokket . It should be fairly easy to write a test that demonstrates it, I should think, and maybe even fix it. The error must be in VersionTheDatabase, I think. I can have a quick look.

**Comment by erikbra** [comment]
@OzBob , we did have a bug related to the version number in the ScriptsRun table not being updated. But I don't think that has anything to to with the issue you reported. 

@wokket struggled to reproduce the original issue you reported. Could you please double-check that you see the same behaviour, if you test again?

**Comment by erikbra** [comment]
Reopened, waiting for comments

**Comment by erikbra** [comment]
Lovely!
