### ISSUE TITLE
--isuptodate

### ISSUE THREAD

**Issue by erikbra** [grate-devs/grate#34]
Just return a true/false of whether the database is up to date or not. No output, just return true on up to date, and false if not.

Implies --disableoutput

**Comment by wokket** [comment]
FYI I started to look into this and it got a bit messy pretty quickly.

RH has a dedicated process for this that is completely separate to the other operations.  I looked into adding a separate command just for IsUpTodate, and also played with hacking it into the existing codepath, and neither one seemed like a super smooth change.

As I have never used this option I'm disinclined to spend too much time fighting with it atm...

**Comment by erikbra** [comment]
Thanks for looking into it. I think using dryrun would solve much of the same use cases. I've never used the isuptodate myself either. I'm thinking a workflow first using --dryrun, then looking at the result, and running without --dryrun would work nicely. I use that approach with helm/helmfile, and I think it's been a good experience up until now.

Should we just park this one, then?

**Comment by wokket** [comment]
Yep, happy to park this until we get a better handle on the use case (or someone to build it out!)
