### ISSUE TITLE
Publish grate docker image to Docker Hub

### ISSUE THREAD

**Issue by wokket** [grate-devs/grate#71]
Once we get a dockerfile added to the repo (via #62) get it published to DockerHub by the release pipeline.

**Comment by erikbra** [comment]
I'm not totally sure how people would use the docker images, though, as opposed to a simple binary. We should definitely add mapping up volumes, etc, in the guidance.

If running in a production (e.g. Kubernetes) cluster, maybe a "watch" mode would be nice? 

Do you use containers with RoundhousE on a day-to-day basis? How do you use them?

**Comment by wokket** [comment]
If people are running a multi-app, multi-db cluster and want real-time push-based deployments they know much more than me about k8s and can provide a demo themselves 🤣   I hadn't realised you were pushing an image like that in the release so I'll go have a look.  My suspicion is it's missing the required i8n libs per https://github.com/erikbra/grate/issues/62#issuecomment-929860708 but I'll find out when I work out how to get an image from a zip...
